# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-27 08:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rsa', '0002_auto_20160327_0800'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='d',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='user',
            name='e',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='user',
            name='n',
            field=models.IntegerField(default=1),
        ),
    ]
